In [1]:
import numpy as np

## Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape(1, 12)
a1

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [4]:
a2 = a.reshape(2, 6)
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a3 = a.reshape(3, 4)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a4 = a.reshape(4, 3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a5 = a.reshape(6, 2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

## Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a1 = a.reshape(1, -1)
a1

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [9]:
a2 = a.reshape(2, -1)
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a3 = a.reshape(3, -1)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a4 = a.reshape(-1, 3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a5 = a.reshape(-1, 2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

## Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

np.arange(12, 24) и np.arange(12, 24).reshape(12, 1) не равны, как минимум у них разный параметр ndim

Первый - набор из 12 данных, второй - набор из 12 массивов, каждый из которых состоит всего из одного числа.

По разному идет обращение к элементам. Но если выписать их на бумагу, то они равны)


## Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [13]:
b = np.random.sample((3, 4)) * 2 - 1
b

array([[ 0.70168388,  0.11167751,  0.24262693, -0.42582071],
       [ 0.73051651,  0.42493985,  0.30894984, -0.05803192],
       [-0.74144177,  0.4977281 , -0.39330228, -0.87683022]])

In [14]:
b1 = b.flatten()
b1

array([ 0.70168388,  0.11167751,  0.24262693, -0.42582071,  0.73051651,
        0.42493985,  0.30894984, -0.05803192, -0.74144177,  0.4977281 ,
       -0.39330228, -0.87683022])

## Задание 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [15]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [16]:
b = np.arange(20, 0, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [17]:
b.ndim == a.ndim

False

In [18]:
a.shape == b.shape

False

Разная размерность и разная форма

## Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [19]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [20]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
v = np.vstack((a, b))
v.size

10

## Задание 9.
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [22]:
A = np.arange(12) #от 0 до 11, т.к. не указано, какую границу не включать, иначе не сработает resize в следующем шаге

In [40]:
A.resize(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [42]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [ ]:
B.shape

In [26]:
np.linalg.det(B)

0.0

обратную матрицу не вычислить, т.к. определитель равен 0

## Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [27]:
np.random.seed(42)


## Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [28]:
c = np.random.randint(0, 16, 16)

In [29]:
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

## Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [30]:
C = c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [31]:
D = C + B * 10
D

array([[  56,  143,  242,  334],
       [ 150,  507,  872, 1224],
       [ 236,  869, 1492, 2126],
       [ 330, 1230, 2127, 3024]])

In [32]:
np.linalg.det(D)

-1741607.9999999756

In [33]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.135368  , -0.09412681, -0.0250975 ,  0.04079219],
       [-0.17297808,  0.16351785,  0.1740805 , -0.16946638],
       [-0.05802224,  0.09496052, -0.10651536,  0.04285695],
       [ 0.09639712, -0.12303113,  0.00685229,  0.03466452]])

## Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C

In [34]:
for i in range(4):
    for j in range(4):
        if D_inv[i][j] > 0:
            D_inv[i][j] = 1
        else:
            D_inv[i][j] = 0

In [35]:
D_inv

array([[1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 1.]])

In [36]:
E = np.zeros((4, 4))

In [37]:
E[np.where(D_inv == 1)] = B[np.where(D_inv == 1)]

In [38]:
E[np.where(D_inv == 0)] = C[np.where(D_inv == 0)]

In [39]:
E

array([[  5.,   3.,  12.,  32.],
       [ 10.,  50.,  86.,   4.],
       [  6.,  86.,   2., 212.],
       [ 32.,  10., 212., 302.]])